repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-diff
        - --args=-write=false
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_documented_variables
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl